-- Insert into Country table
INSERT INTO public."Country" (name, region) VALUES
    ('Afghanistan', 'Asia'),
    ('Albania', 'Europe'),
    ('Algeria', 'Africa'),
    ('Andorra', 'Europe'),
    ('Angola', 'Africa'),
    ('Antigua and Barbuda', 'North_America'),
    ('Argentina', 'South_America'),
    ('Armenia', 'Asia'),
    ('Australia', 'Oceania'),
    ('Austria', 'Europe'),
    ('Azerbaijan', 'Asia'),
    ('Bahamas', 'North_America'),
    ('Bahrain', 'Asia'),
    ('Bangladesh', 'Asia'),
    ('Barbados', 'North_America'),
    ('Belarus', 'Europe'),
    ('Belgium', 'Europe'),
    ('Belize', 'North_America'),
    ('Benin', 'Africa'),
    ('Bhutan', 'Asia'),
    ('Bolivia', 'South_America'),
    ('Bosnia and Herzegovina', 'Europe'),
    ('Botswana', 'Africa'),
    ('Brazil', 'South_America'),
    ('Brunei', 'Asia'),
    ('Bulgaria', 'Europe'),
    ('Burkina Faso', 'Africa'),
    ('Burundi', 'Africa'),
    ('Cabo Verde', 'Africa'),
    ('Cambodia', 'Asia'),
    ('Cameroon', 'Africa'),
    ('Canada', 'North_America'),
    ('Central African Republic', 'Africa'),
    ('Chad', 'Africa'),
    ('Chile', 'South_America'),
    ('China', 'Asia'),
    ('Colombia', 'South_America'),
    ('Comoros', 'Africa'),
    ('Congo (Congo-Brazzaville)', 'Africa'),
    ('Costa Rica', 'North_America'),
    ('Croatia', 'Europe'),
    ('Cuba', 'North_America'),
    ('Cyprus', 'Asia'),
    ('Czechia (Czech Republic)', 'Europe'),
    ('Denmark', 'Europe'),
    ('Djibouti', 'Africa'),
    ('Dominica', 'North_America'),
    ('Dominican Republic', 'North_America'),
    ('Ecuador', 'South_America'),
    ('Egypt', 'Africa'),
    ('El Salvador', 'North_America'),
    ('Equatorial Guinea', 'Africa'),
    ('Eritrea', 'Africa'),
    ('Estonia', 'Europe'),
    ('Eswatini (fmr. "Swaziland")', 'Africa'),
    ('Ethiopia', 'Africa'),
    ('Fiji', 'Oceania'),
    ('Finland', 'Europe'),
    ('France', 'Europe'),
    ('Gabon', 'Africa'),
    ('Gambia', 'Africa'),
    ('Georgia', 'Asia'),
    ('Germany', 'Europe'),
    ('Ghana', 'Africa'),
    ('Greece', 'Europe'),
    ('Grenada', 'North_America'),
    ('Guatemala', 'North_America'),
    ('Guinea', 'Africa'),
    ('Guinea-Bissau', 'Africa'),
    ('Guyana', 'South_America'),
    ('Haiti', 'North_America'),
    ('Holy See', 'Europe'),
    ('Honduras', 'North_America'),
    ('Hungary', 'Europe'),
    ('Iceland', 'Europe'),
    ('India', 'Asia'),
    ('Indonesia', 'Asia'),
    ('Iran', 'Asia'),
    ('Iraq', 'Asia'),
    ('Ireland', 'Europe'),
    ('Israel', 'Asia'),
    ('Italy', 'Europe'),
    ('Jamaica', 'North_America'),
    ('Japan', 'Asia'),
    ('Jordan', 'Asia'),
    ('Kazakhstan', 'Asia'),
    ('Kenya', 'Africa'),
    ('Kiribati', 'Oceania'),
    ('Kuwait', 'Asia'),
    ('Kyrgyzstan', 'Asia'),
    ('Laos', 'Asia'),
    ('Latvia', 'Europe'),
    ('Lebanon', 'Asia'),
    ('Lesotho', 'Africa'),
    ('Liberia', 'Africa'),
    ('Libya', 'Africa'),
    ('Liechtenstein', 'Europe'),
    ('Lithuania', 'Europe'),
    ('Luxembourg', 'Europe'),
    ('Madagascar', 'Africa'),
    ('Malawi', 'Africa'),
    ('Malaysia', 'Asia'),
    ('Maldives', 'Asia'),
    ('Mali', 'Africa'),
    ('Malta', 'Europe'),
    ('Marshall Islands', 'Oceania'),
    ('Mauritania', 'Africa'),
    ('Mauritius', 'Africa'),
    ('Mexico', 'North_America'),
    ('Micronesia', 'Oceania'),
    ('Moldova', 'Europe'),
    ('Monaco', 'Europe'),
    ('Mongolia', 'Asia'),
    ('Montenegro', 'Europe'),
    ('Morocco', 'Africa'),
    ('Mozambique', 'Africa'),
    ('Myanmar (formerly Burma)', 'Asia'),
    ('Namibia', 'Africa'),
    ('Nauru', 'Oceania'),
    ('Nepal', 'Asia'),
    ('Netherlands', 'Europe'),
    ('New Zealand', 'Oceania'),
    ('Nicaragua', 'North_America'),
    ('Niger', 'Africa'),
    ('Nigeria', 'Africa'),
    ('North Korea', 'Asia'),
    ('North Macedonia (formerly Macedonia)', 'Europe'),
    ('Norway', 'Europe'),
    ('Oman', 'Asia'),
    ('Pakistan', 'Asia'),
    ('Palau', 'Oceania'),
    ('Palestine State', 'Asia'),
    ('Panama', 'North_America'),
    ('Papua New Guinea', 'Oceania'),
    ('Paraguay', 'South_America'),
    ('Peru', 'South_America'),
    ('Philippines', 'Asia'),
    ('Poland', 'Europe'),
    ('Portugal', 'Europe'),
    ('Qatar', 'Asia'),
    ('Romania', 'Europe'),
    ('Russia', 'Europe'),
    ('Rwanda', 'Africa'),
    ('Saint Kitts and Nevis', 'North_America'),
    ('Saint Lucia', 'North_America'),
    ('Saint Vincent and the Grenadines', 'North_America'),
    ('Samoa', 'Oceania'),
    ('San Marino', 'Europe'),
    ('Sao Tome and Principe', 'Africa'),
    ('Saudi Arabia', 'Asia'),
    ('Senegal', 'Africa'),
    ('Serbia', 'Europe'),
    ('Seychelles', 'Africa'),
    ('Sierra Leone', 'Africa'),
    ('Singapore', 'Asia'),
    ('Slovakia', 'Europe'),
    ('Slovenia', 'Europe'),
    ('Solomon Islands', 'Oceania'),
    ('Somalia', 'Africa'),
    ('South Africa', 'Africa'),
    ('South Korea', 'Asia'),
    ('South Sudan', 'Africa'),
    ('Spain', 'Europe'),
    ('Sri Lanka', 'Asia'),
    ('Sudan', 'Africa'),
    ('Suriname', 'South_America'),
    ('Sweden', 'Europe'),
    ('Switzerland', 'Europe'),
    ('Syria', 'Asia'),
    ('Tajikistan', 'Asia'),
    ('Tanzania', 'Africa'),
    ('Thailand', 'Asia'),
    ('Timor-Leste', 'Asia'),
    ('Togo', 'Africa'),
    ('Tonga', 'Oceania'),
    ('Trinidad and Tobago', 'North_America'),
    ('Tunisia', 'Africa'),
    ('Turkey', 'Asia'),
    ('Turkmenistan', 'Asia'),
    ('Tuvalu', 'Oceania'),
    ('Uganda', 'Africa'),
    ('Ukraine', 'Europe'),
    ('United Arab Emirates', 'Asia'),
    ('United Kingdom', 'Europe'),
    ('United States', 'North_America'),
    ('Uruguay', 'South_America'),
    ('Uzbekistan', 'Asia'),
    ('Vanuatu', 'Oceania'),
    ('Venezuela', 'South_America'),
    ('Vietnam', 'Asia'),
    ('Yemen', 'Asia'),
    ('Zambia', 'Africa'),
    ('Zimbabwe', 'Africa');
