-- Insert 50 specified countries into Country table
-- (alphabetically sorted – Israel removed, Palestine added)
INSERT INTO public."Country" (name, region, iso_code) VALUES
    ('Algeria', 'Africa', 'dz'),
    ('Argentina', 'South_America', 'ar'),
    ('Australia', 'Oceania', 'au'),
    ('Bangladesh', 'Asia', 'bd'),
    ('Belgium', 'Europe', 'be'),
    ('Brazil', 'South_America', 'br'),
    ('Canada', 'North_America', 'ca'),
    ('Chile', 'South_America', 'cl'),
    ('China', 'Asia', 'cn'),
    ('Colombia', 'South_America', 'co'),
    ('Czechia (Czech Republic)', 'Europe', 'cz'),
    ('Denmark', 'Europe', 'dk'),
    ('Egypt', 'Africa', 'eg'),
    ('Ethiopia', 'Africa', 'et'),
    ('France', 'Europe', 'fr'),
    ('Germany', 'Europe', 'de'),
    ('Greece', 'Europe', 'gr'),
    ('India', 'Asia', 'in'),
    ('Indonesia', 'Asia', 'id'),
    ('Iran', 'Asia', 'ir'),
    ('Iraq', 'Asia', 'iq'),
    ('Italy', 'Europe', 'it'),
    ('Japan', 'Asia', 'jp'),
    ('Kazakhstan', 'Asia', 'kz'),
    ('Malaysia', 'Asia', 'my'),
    ('Mexico', 'North_America', 'mx'),
    ('Morocco', 'Africa', 'ma'),
    ('Netherlands', 'Europe', 'nl'),
    ('Nigeria', 'Africa', 'ng'),
    ('Norway', 'Europe', 'no'),
    ('Pakistan', 'Asia', 'pk'),
    ('Palestine State', 'Asia', 'ps'),
    ('Philippines', 'Asia', 'ph'),
    ('Poland', 'Europe', 'pl'),
    ('Qatar', 'Asia', 'qa'),
    ('Russia', 'Europe', 'ru'),
    ('Saudi Arabia', 'Asia', 'sa'),
    ('Singapore', 'Asia', 'sg'),
    ('South Africa', 'Africa', 'za'),
    ('South Korea', 'Asia', 'kr'),
    ('Spain', 'Europe', 'es'),
    ('Sweden', 'Europe', 'se'),
    ('Switzerland', 'Europe', 'ch'),
    ('Thailand', 'Asia', 'th'),
    ('Turkey', 'Asia', 'tr'),
    ('Ukraine', 'Europe', 'ua'),
    ('United Arab Emirates', 'Asia', 'ae'),
    ('United Kingdom', 'Europe', 'gb'),
    ('United States', 'North_America', 'us'),
    ('Vietnam', 'Asia', 'vn');
