ALTER TABLE public."Country" ADD COLUMN iso_code VARCHAR(2);
UPDATE public."Country" SET iso_code = 'af' WHERE name = 'Afghanistan';
UPDATE public."Country" SET iso_code = 'al' WHERE name = 'Albania';
UPDATE public."Country" SET iso_code = 'dz' WHERE name = 'Algeria';
UPDATE public."Country" SET iso_code = 'ad' WHERE name = 'Andorra';
UPDATE public."Country" SET iso_code = 'ao' WHERE name = 'Angola';
UPDATE public."Country" SET iso_code = 'ag' WHERE name = 'Antigua and Barbuda';
UPDATE public."Country" SET iso_code = 'ar' WHERE name = 'Argentina';
UPDATE public."Country" SET iso_code = 'am' WHERE name = 'Armenia';
UPDATE public."Country" SET iso_code = 'au' WHERE name = 'Australia';
UPDATE public."Country" SET iso_code = 'at' WHERE name = 'Austria';
UPDATE public."Country" SET iso_code = 'az' WHERE name = 'Azerbaijan';
UPDATE public."Country" SET iso_code = 'bs' WHERE name = 'Bahamas';
UPDATE public."Country" SET iso_code = 'bh' WHERE name = 'Bahrain';
UPDATE public."Country" SET iso_code = 'bd' WHERE name = 'Bangladesh';
UPDATE public."Country" SET iso_code = 'bb' WHERE name = 'Barbados';
UPDATE public."Country" SET iso_code = 'by' WHERE name = 'Belarus';
UPDATE public."Country" SET iso_code = 'be' WHERE name = 'Belgium';
UPDATE public."Country" SET iso_code = 'bz' WHERE name = 'Belize';
UPDATE public."Country" SET iso_code = 'bj' WHERE name = 'Benin';
UPDATE public."Country" SET iso_code = 'bt' WHERE name = 'Bhutan';
UPDATE public."Country" SET iso_code = 'bo' WHERE name = 'Bolivia';
UPDATE public."Country" SET iso_code = 'ba' WHERE name = 'Bosnia and Herzegovina';
UPDATE public."Country" SET iso_code = 'bw' WHERE name = 'Botswana';
UPDATE public."Country" SET iso_code = 'br' WHERE name = 'Brazil';
UPDATE public."Country" SET iso_code = 'bn' WHERE name = 'Brunei';
UPDATE public."Country" SET iso_code = 'bg' WHERE name = 'Bulgaria';
UPDATE public."Country" SET iso_code = 'bf' WHERE name = 'Burkina Faso';
UPDATE public."Country" SET iso_code = 'bi' WHERE name = 'Burundi';
UPDATE public."Country" SET iso_code = 'cv' WHERE name = 'Cabo Verde';
UPDATE public."Country" SET iso_code = 'kh' WHERE name = 'Cambodia';
UPDATE public."Country" SET iso_code = 'cm' WHERE name = 'Cameroon';
UPDATE public."Country" SET iso_code = 'ca' WHERE name = 'Canada';
UPDATE public."Country" SET iso_code = 'cf' WHERE name = 'Central African Republic';
UPDATE public."Country" SET iso_code = 'td' WHERE name = 'Chad';
UPDATE public."Country" SET iso_code = 'cl' WHERE name = 'Chile';
UPDATE public."Country" SET iso_code = 'cn' WHERE name = 'China';
UPDATE public."Country" SET iso_code = 'co' WHERE name = 'Colombia';
UPDATE public."Country" SET iso_code = 'km' WHERE name = 'Comoros';
UPDATE public."Country" SET iso_code = 'cg' WHERE name = 'Congo (Congo-Brazzaville)';
UPDATE public."Country" SET iso_code = 'cr' WHERE name = 'Costa Rica';
UPDATE public."Country" SET iso_code = 'hr' WHERE name = 'Croatia';
UPDATE public."Country" SET iso_code = 'cu' WHERE name = 'Cuba';
UPDATE public."Country" SET iso_code = 'cy' WHERE name = 'Cyprus';
UPDATE public."Country" SET iso_code = 'cz' WHERE name = 'Czechia (Czech Republic)';
UPDATE public."Country" SET iso_code = 'dk' WHERE name = 'Denmark';
UPDATE public."Country" SET iso_code = 'dj' WHERE name = 'Djibouti';
UPDATE public."Country" SET iso_code = 'dm' WHERE name = 'Dominica';
UPDATE public."Country" SET iso_code = 'do' WHERE name = 'Dominican Republic';
UPDATE public."Country" SET iso_code = 'ec' WHERE name = 'Ecuador';
UPDATE public."Country" SET iso_code = 'eg' WHERE name = 'Egypt';
UPDATE public."Country" SET iso_code = 'sv' WHERE name = 'El Salvador';
UPDATE public."Country" SET iso_code = 'gq' WHERE name = 'Equatorial Guinea';
UPDATE public."Country" SET iso_code = 'er' WHERE name = 'Eritrea';
UPDATE public."Country" SET iso_code = 'ee' WHERE name = 'Estonia';
UPDATE public."Country" SET iso_code = 'sz' WHERE name = 'Eswatini (fmr. "Swaziland")';
UPDATE public."Country" SET iso_code = 'et' WHERE name = 'Ethiopia';
UPDATE public."Country" SET iso_code = 'fj' WHERE name = 'Fiji';
UPDATE public."Country" SET iso_code = 'fi' WHERE name = 'Finland';
UPDATE public."Country" SET iso_code = 'fr' WHERE name = 'France';
UPDATE public."Country" SET iso_code = 'ga' WHERE name = 'Gabon';
UPDATE public."Country" SET iso_code = 'gm' WHERE name = 'Gambia';
UPDATE public."Country" SET iso_code = 'ge' WHERE name = 'Georgia';
UPDATE public."Country" SET iso_code = 'de' WHERE name = 'Germany';
UPDATE public."Country" SET iso_code = 'gh' WHERE name = 'Ghana';
UPDATE public."Country" SET iso_code = 'gr' WHERE name = 'Greece';
UPDATE public."Country" SET iso_code = 'gd' WHERE name = 'Grenada';
UPDATE public."Country" SET iso_code = 'gt' WHERE name = 'Guatemala';
UPDATE public."Country" SET iso_code = 'gn' WHERE name = 'Guinea';
UPDATE public."Country" SET iso_code = 'gw' WHERE name = 'Guinea-Bissau';
UPDATE public."Country" SET iso_code = 'gy' WHERE name = 'Guyana';
UPDATE public."Country" SET iso_code = 'ht' WHERE name = 'Haiti';
UPDATE public."Country" SET iso_code = 'va' WHERE name = 'Holy See';
UPDATE public."Country" SET iso_code = 'hn' WHERE name = 'Honduras';
UPDATE public."Country" SET iso_code = 'hu' WHERE name = 'Hungary';
UPDATE public."Country" SET iso_code = 'is' WHERE name = 'Iceland';
UPDATE public."Country" SET iso_code = 'in' WHERE name = 'India';
UPDATE public."Country" SET iso_code = 'id' WHERE name = 'Indonesia';
UPDATE public."Country" SET iso_code = 'ir' WHERE name = 'Iran';
UPDATE public."Country" SET iso_code = 'iq' WHERE name = 'Iraq';
UPDATE public."Country" SET iso_code = 'ie' WHERE name = 'Ireland';
UPDATE public."Country" SET iso_code = 'il' WHERE name = 'Israel';
UPDATE public."Country" SET iso_code = 'it' WHERE name = 'Italy';
UPDATE public."Country" SET iso_code = 'jm' WHERE name = 'Jamaica';
UPDATE public."Country" SET iso_code = 'jp' WHERE name = 'Japan';
UPDATE public."Country" SET iso_code = 'jo' WHERE name = 'Jordan';
UPDATE public."Country" SET iso_code = 'kz' WHERE name = 'Kazakhstan';
UPDATE public."Country" SET iso_code = 'ke' WHERE name = 'Kenya';
UPDATE public."Country" SET iso_code = 'ki' WHERE name = 'Kiribati';
UPDATE public."Country" SET iso_code = 'kw' WHERE name = 'Kuwait';
UPDATE public."Country" SET iso_code = 'kg' WHERE name = 'Kyrgyzstan';
UPDATE public."Country" SET iso_code = 'la' WHERE name = 'Laos';
UPDATE public."Country" SET iso_code = 'lv' WHERE name = 'Latvia';
UPDATE public."Country" SET iso_code = 'lb' WHERE name = 'Lebanon';
UPDATE public."Country" SET iso_code = 'ls' WHERE name = 'Lesotho';
UPDATE public."Country" SET iso_code = 'lr' WHERE name = 'Liberia';
UPDATE public."Country" SET iso_code = 'ly' WHERE name = 'Libya';
UPDATE public."Country" SET iso_code = 'li' WHERE name = 'Liechtenstein';
UPDATE public."Country" SET iso_code = 'lt' WHERE name = 'Lithuania';
UPDATE public."Country" SET iso_code = 'lu' WHERE name = 'Luxembourg';
UPDATE public."Country" SET iso_code = 'mo' WHERE name = 'Macao';
UPDATE public."Country" SET iso_code = 'mg' WHERE name = 'Madagascar';
UPDATE public."Country" SET iso_code = 'mw' WHERE name = 'Malawi';
UPDATE public."Country" SET iso_code = 'my' WHERE name = 'Malaysia';
UPDATE public."Country" SET iso_code = 'mv' WHERE name = 'Maldives';
UPDATE public."Country" SET iso_code = 'ml' WHERE name = 'Mali';
UPDATE public."Country" SET iso_code = 'mt' WHERE name = 'Malta';
UPDATE public."Country" SET iso_code = 'mh' WHERE name = 'Marshall Islands';
UPDATE public."Country" SET iso_code = 'mq' WHERE name = 'Martinique';
UPDATE public."Country" SET iso_code = 'mr' WHERE name = 'Mauritania';
UPDATE public."Country" SET iso_code = 'mu' WHERE name = 'Mauritius';
UPDATE public."Country" SET iso_code = 'yt' WHERE name = 'Mayotte';
UPDATE public."Country" SET iso_code = 'mx' WHERE name = 'Mexico';
UPDATE public."Country" SET iso_code = 'fm' WHERE name = 'Micronesia';
UPDATE public."Country" SET iso_code = 'md' WHERE name = 'Moldova';
UPDATE public."Country" SET iso_code = 'mc' WHERE name = 'Monaco';
UPDATE public."Country" SET iso_code = 'mn' WHERE name = 'Mongolia';
UPDATE public."Country" SET iso_code = 'me' WHERE name = 'Montenegro';
UPDATE public."Country" SET iso_code = 'ma' WHERE name = 'Morocco';
UPDATE public."Country" SET iso_code = 'mz' WHERE name = 'Mozambique';
UPDATE public."Country" SET iso_code = 'mm' WHERE name = 'Myanmar (Burma)';
UPDATE public."Country" SET iso_code = 'na' WHERE name = 'Namibia';
UPDATE public."Country" SET iso_code = 'nr' WHERE name = 'Nauru';
UPDATE public."Country" SET iso_code = 'np' WHERE name = 'Nepal';
UPDATE public."Country" SET iso_code = 'nl' WHERE name = 'Netherlands';
UPDATE public."Country" SET iso_code = 'nc' WHERE name = 'New Caledonia';
UPDATE public."Country" SET iso_code = 'nz' WHERE name = 'New Zealand';
UPDATE public."Country" SET iso_code = 'ni' WHERE name = 'Nicaragua';
UPDATE public."Country" SET iso_code = 'ne' WHERE name = 'Niger';
UPDATE public."Country" SET iso_code = 'ng' WHERE name = 'Nigeria';
UPDATE public."Country" SET iso_code = 'nu' WHERE name = 'Niue';
UPDATE public."Country" SET iso_code = 'nf' WHERE name = 'Norfolk Island';
UPDATE public."Country" SET iso_code = 'mp' WHERE name = 'Northern Mariana Islands';
UPDATE public."Country" SET iso_code = 'no' WHERE name = 'Norway';
UPDATE public."Country" SET iso_code = 'om' WHERE name = 'Oman';
UPDATE public."Country" SET iso_code = 'pk' WHERE name = 'Pakistan';
UPDATE public."Country" SET iso_code = 'pw' WHERE name = 'Palau';
UPDATE public."Country" SET iso_code = 'ps' WHERE name = 'Palestine';
UPDATE public."Country" SET iso_code = 'pa' WHERE name = 'Panama';
UPDATE public."Country" SET iso_code = 'pg' WHERE name = 'Papua New Guinea';
UPDATE public."Country" SET iso_code = 'py' WHERE name = 'Paraguay';
UPDATE public."Country" SET iso_code = 'pe' WHERE name = 'Peru';
UPDATE public."Country" SET iso_code = 'ph' WHERE name = 'Philippines';
UPDATE public."Country" SET iso_code = 'pl' WHERE name = 'Poland';
UPDATE public."Country" SET iso_code = 'pt' WHERE name = 'Portugal';
UPDATE public."Country" SET iso_code = 'pr' WHERE name = 'Puerto Rico';
UPDATE public."Country" SET iso_code = 'qa' WHERE name = 'Qatar';
UPDATE public."Country" SET iso_code = 're' WHERE name = 'Réunion';
UPDATE public."Country" SET iso_code = 'ro' WHERE name = 'Romania';
UPDATE public."Country" SET iso_code = 'ru' WHERE name = 'Russia';
UPDATE public."Country" SET iso_code = 'rw' WHERE name = 'Rwanda';
UPDATE public."Country" SET iso_code = 'sa' WHERE name = 'Saudi Arabia';
UPDATE public."Country" SET iso_code = 'sn' WHERE name = 'Senegal';
UPDATE public."Country" SET iso_code = 'rs' WHERE name = 'Serbia';
UPDATE public."Country" SET iso_code = 'sc' WHERE name = 'Seychelles';
UPDATE public."Country" SET iso_code = 'sl' WHERE name = 'Sierra Leone';
UPDATE public."Country" SET iso_code = 'sg' WHERE name = 'Singapore';
UPDATE public."Country" SET iso_code = 'sx' WHERE name = 'Sint Maarten';
UPDATE public."Country" SET iso_code = 'sk' WHERE name = 'Slovakia';
UPDATE public."Country" SET iso_code = 'si' WHERE name = 'Slovenia';
UPDATE public."Country" SET iso_code = 'sb' WHERE name = 'Solomon Islands';
UPDATE public."Country" SET iso_code = 'so' WHERE name = 'Somalia';
UPDATE public."Country" SET iso_code = 'za' WHERE name = 'South Africa';
UPDATE public."Country" SET iso_code = 'gs' WHERE name = 'South Georgia & South Sandwich Islands';
UPDATE public."Country" SET iso_code = 'ss' WHERE name = 'South Sudan';
UPDATE public."Country" SET iso_code = 'es' WHERE name = 'Spain';
UPDATE public."Country" SET iso_code = 'lk' WHERE name = 'Sri Lanka';
UPDATE public."Country" SET iso_code = 'sd' WHERE name = 'Sudan';
UPDATE public."Country" SET iso_code = 'sr' WHERE name = 'Suriname';
UPDATE public."Country" SET iso_code = 'sj' WHERE name = 'Svalbard and Jan Mayen';
UPDATE public."Country" SET iso_code = 'se' WHERE name = 'Sweden';
UPDATE public."Country" SET iso_code = 'ch' WHERE name = 'Switzerland';
UPDATE public."Country" SET iso_code = 'sy' WHERE name = 'Syria';
UPDATE public."Country" SET iso_code = 'tw' WHERE name = 'Taiwan';
UPDATE public."Country" SET iso_code = 'tj' WHERE name = 'Tajikistan';
UPDATE public."Country" SET iso_code = 'tz' WHERE name = 'Tanzania';
UPDATE public."Country" SET iso_code = 'th' WHERE name = 'Thailand';
UPDATE public."Country" SET iso_code = 'tg' WHERE name = 'Togo';
UPDATE public."Country" SET iso_code = 'tk' WHERE name = 'Tokelau';
UPDATE public."Country" SET iso_code = 'to' WHERE name = 'Tonga';
UPDATE public."Country" SET iso_code = 'tt' WHERE name = 'Trinidad and Tobago';
UPDATE public."Country" SET iso_code = 'tn' WHERE name = 'Tunisia';
UPDATE public."Country" SET iso_code = 'tr' WHERE name = 'Turkey';
UPDATE public."Country" SET iso_code = 'tm' WHERE name = 'Turkmenistan';
UPDATE public."Country" SET iso_code = 'tc' WHERE name = 'Turks and Caicos Islands';
UPDATE public."Country" SET iso_code = 'tv' WHERE name = 'Tuvalu';
UPDATE public."Country" SET iso_code = 'ug' WHERE name = 'Uganda';
UPDATE public."Country" SET iso_code = 'ua' WHERE name = 'Ukraine';
UPDATE public."Country" SET iso_code = 'ae' WHERE name = 'United Arab Emirates';
UPDATE public."Country" SET iso_code = 'gb' WHERE name = 'United Kingdom';
UPDATE public."Country" SET iso_code = 'us' WHERE name = 'United States of America';
UPDATE public."Country" SET iso_code = 'uy' WHERE name = 'Uruguay';
UPDATE public."Country" SET iso_code = 'uz' WHERE name = 'Uzbekistan';
UPDATE public."Country" SET iso_code = 'vu' WHERE name = 'Vanuatu';
UPDATE public."Country" SET iso_code = 've' WHERE name = 'Venezuela';
UPDATE public."Country" SET iso_code = 'vn' WHERE name = 'Vietnam';
UPDATE public."Country" SET iso_code = 'wf' WHERE name = 'Wallis and Futuna';
UPDATE public."Country" SET iso_code = 'ye' WHERE name = 'Yemen';
UPDATE public."Country" SET iso_code = 'zm' WHERE name = 'Zambia';
UPDATE public."Country" SET iso_code = 'zw' WHERE name = 'Zimbabwe';