-- Insert into Country table with lowercase iso_code
INSERT INTO public."Country" (name, region, iso_code) VALUES
    ('Afghanistan', 'Asia', 'af'),
    ('Albania', 'Europe', 'al'),
    ('Algeria', 'Africa', 'dz'),
    ('Andorra', 'Europe', 'ad'),
    ('Angola', 'Africa', 'ao'),
    ('Antigua and Barbuda', 'North_America', 'ag'),
    ('Argentina', 'South_America', 'ar'),
    ('Armenia', 'Asia', 'am'),
    ('Australia', 'Oceania', 'au'),
    ('Austria', 'Europe', 'at'),
    ('Azerbaijan', 'Asia', 'az'),
    ('Bahamas', 'North_America', 'bs'),
    ('Bahrain', 'Asia', 'bh'),
    ('Bangladesh', 'Asia', 'bd'),
    ('Barbados', 'North_America', 'bb'),
    ('Belarus', 'Europe', 'by'),
    ('Belgium', 'Europe', 'be'),
    ('Belize', 'North_America', 'bz'),
    ('Benin', 'Africa', 'bj'),
    ('Bhutan', 'Asia', 'bt'),
    ('Bolivia', 'South_America', 'bo'),
    ('Bosnia and Herzegovina', 'Europe', 'ba'),
    ('Botswana', 'Africa', 'bw'),
    ('Brazil', 'South_America', 'br'),
    ('Brunei', 'Asia', 'bn'),
    ('Bulgaria', 'Europe', 'bg'),
    ('Burkina Faso', 'Africa', 'bf'),
    ('Burundi', 'Africa', 'bi'),
    ('Cabo Verde', 'Africa', 'cv'),
    ('Cambodia', 'Asia', 'kh'),
    ('Cameroon', 'Africa', 'cm'),
    ('Canada', 'North_America', 'ca'),
    ('Central African Republic', 'Africa', 'cf'),
    ('Chad', 'Africa', 'td'),
    ('Chile', 'South_America', 'cl'),
    ('China', 'Asia', 'cn'),
    ('Colombia', 'South_America', 'co'),
    ('Comoros', 'Africa', 'km'),
    ('Congo (Congo-Brazzaville)', 'Africa', 'cg'),
    ('Costa Rica', 'North_America', 'cr'),
    ('Croatia', 'Europe', 'hr'),
    ('Cuba', 'North_America', 'cu'),
    ('Cyprus', 'Asia', 'cy'),
    ('Czechia (Czech Republic)', 'Europe', 'cz'),
    ('Denmark', 'Europe', 'dk'),
    ('Djibouti', 'Africa', 'dj'),
    ('Dominica', 'North_America', 'dm'),
    ('Dominican Republic', 'North_America', 'do'),
    ('Ecuador', 'South_America', 'ec'),
    ('Egypt', 'Africa', 'eg'),
    ('El Salvador', 'North_America', 'sv'),
    ('Equatorial Guinea', 'Africa', 'gq'),
    ('Eritrea', 'Africa', 'er'),
    ('Estonia', 'Europe', 'ee'),
    ('Eswatini (fmr. "Swaziland")', 'Africa', 'sz'),
    ('Ethiopia', 'Africa', 'et'),
    ('Fiji', 'Oceania', 'fj'),
    ('Finland', 'Europe', 'fi'),
    ('France', 'Europe', 'fr'),
    ('Gabon', 'Africa', 'ga'),
    ('Gambia', 'Africa', 'gm'),
    ('Georgia', 'Asia', 'ge'),
    ('Germany', 'Europe', 'de'),
    ('Ghana', 'Africa', 'gh'),
    ('Greece', 'Europe', 'gr'),
    ('Grenada', 'North_America', 'gd'),
    ('Guatemala', 'North_America', 'gt'),
    ('Guinea', 'Africa', 'gn'),
    ('Guinea-Bissau', 'Africa', 'gw'),
    ('Guyana', 'South_America', 'gy'),
    ('Haiti', 'North_America', 'ht'),
    ('Holy See', 'Europe', 'va'),
    ('Honduras', 'North_America', 'hn'),
    ('Hungary', 'Europe', 'hu'),
    ('Iceland', 'Europe', 'is'),
    ('India', 'Asia', 'in'),
    ('Indonesia', 'Asia', 'id'),
    ('Iran', 'Asia', 'ir'),
    ('Iraq', 'Asia', 'iq'),
    ('Ireland', 'Europe', 'ie'),
    ('Israel', 'Asia', 'il'),
    ('Italy', 'Europe', 'it'),
    ('Jamaica', 'North_America', 'jm'),
    ('Japan', 'Asia', 'jp'),
    ('Jordan', 'Asia', 'jo'),
    ('Kazakhstan', 'Asia', 'kz'),
    ('Kenya', 'Africa', 'ke'),
    ('Kiribati', 'Oceania', 'ki'),
    ('Kuwait', 'Asia', 'kw'),
    ('Kyrgyzstan', 'Asia', 'kg'),
    ('Laos', 'Asia', 'la'),
    ('Latvia', 'Europe', 'lv'),
    ('Lebanon', 'Asia', 'lb'),
    ('Lesotho', 'Africa', 'ls'),
    ('Liberia', 'Africa', 'lr'),
    ('Libya', 'Africa', 'ly'),
    ('Liechtenstein', 'Europe', 'li'),
    ('Lithuania', 'Europe', 'lt'),
    ('Luxembourg', 'Europe', 'lu'),
    ('Madagascar', 'Africa', 'mg'),
    ('Malawi', 'Africa', 'mw'),
    ('Malaysia', 'Asia', 'my'),
    ('Maldives', 'Asia', 'mv'),
    ('Mali', 'Africa', 'ml'),
    ('Malta', 'Europe', 'mt'),
    ('Marshall Islands', 'Oceania', 'mh'),
    ('Mauritania', 'Africa', 'mr'),
    ('Mauritius', 'Africa', 'mu'),
    ('Mexico', 'North_America', 'mx'),
    ('Micronesia', 'Oceania', 'fm'),
    ('Moldova', 'Europe', 'md'),
    ('Monaco', 'Europe', 'mc'),
    ('Mongolia', 'Asia', 'mn'),
    ('Montenegro', 'Europe', 'me'),
    ('Morocco', 'Africa', 'ma'),
    ('Mozambique', 'Africa', 'mz'),
    ('Myanmar (formerly Burma)', 'Asia', 'mm'),
    ('Namibia', 'Africa', 'na'),
    ('Nauru', 'Oceania', 'nr'),
    ('Nepal', 'Asia', 'np'),
    ('Netherlands', 'Europe', 'nl'),
    ('New Zealand', 'Oceania', 'nz'),
    ('Nicaragua', 'North_America', 'ni'),
    ('Niger', 'Africa', 'ne'),
    ('Nigeria', 'Africa', 'ng'),
    ('North Korea', 'Asia', 'kp'),
    ('North Macedonia (formerly Macedonia)', 'Europe', 'mk'),
    ('Norway', 'Europe', 'no'),
    ('Oman', 'Asia', 'om'),
    ('Pakistan', 'Asia', 'pk'),
    ('Palau', 'Oceania', 'pw'),
    ('Palestine State', 'Asia', 'ps'),
    ('Panama', 'North_America', 'pa'),
    ('Papua New Guinea', 'Oceania', 'pg'),
    ('Paraguay', 'South_America', 'py'),
    ('Peru', 'South_America', 'pe'),
    ('Philippines', 'Asia', 'ph'),
    ('Poland', 'Europe', 'pl'),
    ('Portugal', 'Europe', 'pt'),
    ('Qatar', 'Asia', 'qa'),
    ('Romania', 'Europe', 'ro'),
    ('Russia', 'Europe', 'ru'),
    ('Rwanda', 'Africa', 'rw'),
    ('Saint Kitts and Nevis', 'North_America', 'kn'),
    ('Saint Lucia', 'North_America', 'lc'),
    ('Saint Vincent and the Grenadines', 'North_America', 'vc'),
    ('Samoa', 'Oceania', 'ws'),
    ('San Marino', 'Europe', 'sm'),
    ('Sao Tome and Principe', 'Africa', 'st'),
    ('Saudi Arabia', 'Asia', 'sa'),
    ('Senegal', 'Africa', 'sn'),
    ('Serbia', 'Europe', 'rs'),
    ('Seychelles', 'Africa', 'sc'),
    ('Sierra Leone', 'Africa', 'sl'),
    ('Singapore', 'Asia', 'sg'),
    ('Slovakia', 'Europe', 'sk'),
    ('Slovenia', 'Europe', 'si'),
    ('Solomon Islands', 'Oceania', 'sb'),
    ('Somalia', 'Africa', 'so'),
    ('South Africa', 'Africa', 'za'),
    ('South Korea', 'Asia', 'kr'),
    ('South Sudan', 'Africa', 'ss'),
    ('Spain', 'Europe', 'es'),
    ('Sri Lanka', 'Asia', 'lk'),
    ('Sudan', 'Africa', 'sd'),
    ('Suriname', 'South_America', 'sr'),
    ('Sweden', 'Europe', 'se'),
    ('Switzerland', 'Europe', 'ch'),
    ('Syria', 'Asia', 'sy'),
    ('Tajikistan', 'Asia', 'tj'),
    ('Tanzania', 'Africa', 'tz'),
    ('Thailand', 'Asia', 'th'),
    ('Timor-Leste', 'Asia', 'tl'),
    ('Togo', 'Africa', 'tg'),
    ('Tonga', 'Oceania', 'to'),
    ('Trinidad and Tobago', 'North_America', 'tt'),
    ('Tunisia', 'Africa', 'tn'),
    ('Turkey', 'Asia', 'tr'),
    ('Turkmenistan', 'Asia', 'tm'),
    ('Tuvalu', 'Oceania', 'tv'),
    ('Uganda', 'Africa', 'ug'),
    ('Ukraine', 'Europe', 'ua'),
    ('United Arab Emirates', 'Asia', 'ae'),
    ('United Kingdom', 'Europe', 'gb'),
    ('United States', 'North_America', 'us'),
    ('Uruguay', 'South_America', 'uy'),
    ('Uzbekistan', 'Asia', 'uz'),
    ('Vanuatu', 'Oceania', 'vu'),
    ('Venezuela', 'South_America', 've'),
    ('Vietnam', 'Asia', 'vn'),
    ('Yemen', 'Asia', 'ye'),
    ('Zambia', 'Africa', 'zm'),
    ('Zimbabwe', 'Africa', 'zw');
